### ISSUE TITLE
Power board from Edison-Ethernet block

### ISSUE THREAD

**Issue by mountainraptor** [LGSInnovations/Edison-Ethernet#2]
Being able to power the board via the Edison-Ethernet block would eliminate the need for the Base Block.  It may be nice to also add a FTDI chip on the Ethernet-Edison block.

**Comment by asagraf** [comment]
It's worth noting that the board operating both its USB and Ethernet port at full capabilities draws very nearly the maximum current that the Edison can provide on its 3.3V rails. Adding an onboard power supply would allow us to design one with sufficient "breathing room."

By doing this, we would essentially be exactly replicating the Sparkfun Base Block (with the exception of the OTG port), right?
