### ISSUE TITLE
Compiled version of smsc95xx for kernel 3.10.98

### ISSUE THREAD

**Issue by mzavatta** [LGSInnovations/Edison-Ethernet#5]
Latest official Edison image (rel 3.5) comes with kernel 3.10.98. Would like to add Ethernet support to this image version. Would it be possible for you to provide the compiled ko files for 3.10.98? Thanks!

**Comment by mountainraptor** [comment]
All of the source necessary to move to a newer kernel is available here, we have no plans to update to a newer kernel.
